services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lista-tarefas-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080

  backend:
    build:
      context: ./Api Tarefas/Api-Tarefas
      dockerfile: Dockerfile
    container_name: lista-tarefas-backend
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/lista_tarefas
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  mariadb:
    image: mariadb:11
    container_name: lista-tarefas-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: lista_tarefas
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: